"use client";
import Head from "next/head";
import ResourcePage from "../components/pages/resource";


export default function Index() {
  return (
    <>
      <Head>
        <title>Chanchal Veer Foundation</title>
        <link rel="icon" href="/logo.png" />
        {/* Meta Tags Dynamically generated by metaseo.itsvg.in */}
        <meta name="title" content="Chanchal Veer Foundation" />
        <meta
          name="description"
          content="We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger."
        />
        <meta name="copyright" content="Chanchal Veer Foundation" />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://chanchalveer.org" />
        <meta property="og:title" content="Chanchal Veer Foundation" />
        <meta
          property="og:description"
          content="We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger."
        />
        <meta property="og:image" content="https://chanchalveer.org/og.png" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://chanchalveer.org" />
        <meta property="twitter:title" content="Chanchal Veer Foundation" />
        <meta
          property="twitter:description"
          content="We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger."
        />
        <meta property="twitter:image" content="https://chanchalveer.org/og.png" />
      </Head>
      <ResourcePage />
    </>
  );
}
